#!/usr/bin/env bash
set -euo pipefail

script_dir="$(dirname "$(readlink -f "$0")")"
cd "$script_dir/.."

single () {
	inkscape --export-area-page -o "png/$3-$1x$2.png" --export-width="$1" --export-height="$2" "src/$3.svg"
}

exp () {
	single "$1" "$1" siren
	single "$1" "$1" siren-back
	single "$1" "$1" siren-tri
}

exp 1024

single 1024 410 siren-stripchat
